### ISSUE TITLE
SIGPIPE breaks imu_service

### ISSUE THREAD

**Issue by idontwanto** [achyeboah/robot#1]
if client disconnects prematurely imu_service receives SIGPIPE - no handle defined means imu_service quits permanently

**Comment by achyeboah** [comment]
> if client disconnects prematurely imu_service receives SIGPIPE - no handle defined means imu_service quits permanently

confirmed... will work on this

**Comment by achyeboah** [comment]
closed by #3

**Comment by achyeboah** [comment]
closed by #3
